/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { SteelProfileData, SteelProperties, WoodProperties } from '../types';

// ============================================================================
// 1. EXTENDED STEEL PROFILES CATALOG (LAMINADOS EN CALIENTE Y CONFORMADOS EN FRÍO)
// ============================================================================

export interface ExtendedSteelProfile extends SteelProfileData {
  category: 'hot_rolled' | 'cold_formed';
  family: 'IPN' | 'IPE' | 'HEB' | 'HEA' | 'UPN' | 'W_SHAPE' | 'C_CHANNEL' | 'Z_PROFILE' | 'HSS_RECT' | 'HSS_ROUND';
  standardRef: string; // ej: "EN 10025 / EN 10034", "ASTM A6", "EN 10219 (Conformado en frío)"
  weightKgM: number;
  Welx: number; // cm³ módulo elástico fuerte
  Wely: number; // cm³ módulo elástico débil
  description: string;
}

export const COMPLETE_STEEL_CATALOG: ExtendedSteelProfile[] = [
  // --------------------------------------------------------------------------
  // PERFILES IPN (Vigas I de alas inclinadas - Laminados en caliente EN 10024)
  // --------------------------------------------------------------------------
  {
    id: 'IPN_160',
    type: 'W_SHAPE',
    category: 'hot_rolled',
    family: 'IPN',
    designation: 'IPN 160',
    standardRef: 'UNE-EN 10024 / NC Acero',
    d: 160,
    b: 74,
    tw: 6.3,
    tf: 9.5,
    A: 22.8,
    Ix: 935,
    Iy: 54.7,
    rx: 6.4,
    ry: 1.55,
    Welx: 117,
    Wely: 14.8,
    Zx: 138,
    Zy: 24.2,
    weightKgM: 17.9,
    description: 'Perfil doble T normalizado de 160 mm de altura con alas inclinadas.',
  },
  {
    id: 'IPN_200',
    type: 'W_SHAPE',
    category: 'hot_rolled',
    family: 'IPN',
    designation: 'IPN 200',
    standardRef: 'UNE-EN 10024 / NC Acero',
    d: 200,
    b: 90,
    tw: 7.5,
    tf: 11.3,
    A: 33.4,
    Ix: 2140,
    Iy: 117,
    rx: 8.0,
    ry: 1.87,
    Welx: 214,
    Wely: 26.0,
    Zx: 250,
    Zy: 43.5,
    weightKgM: 26.2,
    description: 'Perfil IPN 200 para columnas y soportes de edificaciones intermedias.',
  },
  {
    id: 'IPN_240',
    type: 'W_SHAPE',
    category: 'hot_rolled',
    family: 'IPN',
    designation: 'IPN 240',
    standardRef: 'UNE-EN 10024 / NC Acero',
    d: 240,
    b: 106,
    tw: 8.7,
    tf: 13.1,
    A: 46.1,
    Ix: 4250,
    Iy: 221,
    rx: 9.59,
    ry: 2.19,
    Welx: 354,
    Wely: 41.7,
    Zx: 418,
    Zy: 71.3,
    weightKgM: 36.2,
    description: 'Perfil IPN 240 para marcos estructurales con cargas moderadas.',
  },
  {
    id: 'IPN_300',
    type: 'W_SHAPE',
    category: 'hot_rolled',
    family: 'IPN',
    designation: 'IPN 300',
    standardRef: 'UNE-EN 10024 / NC Acero',
    d: 300,
    b: 125,
    tw: 10.8,
    tf: 16.2,
    A: 69.0,
    Ix: 9800,
    Iy: 451,
    rx: 11.9,
    ry: 2.56,
    Welx: 653,
    Wely: 72.2,
    Zx: 778,
    Zy: 126,
    weightKgM: 54.2,
    description: 'Perfil IPN 300 de alta capacidad a flexión en eje fuerte.',
  },

  // --------------------------------------------------------------------------
  // PERFILES IPE (Vigas I de alas paralelas - Laminados en caliente EN 10034)
  // --------------------------------------------------------------------------
  {
    id: 'IPE_160',
    type: 'W_SHAPE',
    category: 'hot_rolled',
    family: 'IPE',
    designation: 'IPE 160',
    standardRef: 'EN 10034 / Eurocódigo 3',
    d: 160,
    b: 82,
    tw: 5.0,
    tf: 7.4,
    A: 20.1,
    Ix: 869,
    Iy: 68.3,
    rx: 6.58,
    ry: 1.84,
    Welx: 109,
    Wely: 16.7,
    Zx: 124,
    Zy: 26.1,
    weightKgM: 15.8,
    description: 'Perfil IPE estándar europeo de alas paralelas.',
  },
  {
    id: 'IPE_200',
    type: 'W_SHAPE',
    category: 'hot_rolled',
    family: 'IPE',
    designation: 'IPE 200',
    standardRef: 'EN 10034 / Eurocódigo 3',
    d: 200,
    b: 100,
    tw: 5.6,
    tf: 8.5,
    A: 28.5,
    Ix: 1940,
    Iy: 142,
    rx: 8.26,
    ry: 2.24,
    Welx: 194,
    Wely: 28.5,
    Zx: 221,
    Zy: 44.6,
    weightKgM: 22.4,
    description: 'Perfil IPE 200 versátil para columnas arriostradas y naves.',
  },
  {
    id: 'IPE_240',
    type: 'W_SHAPE',
    category: 'hot_rolled',
    family: 'IPE',
    designation: 'IPE 240',
    standardRef: 'EN 10034 / Eurocódigo 3',
    d: 240,
    b: 120,
    tw: 6.2,
    tf: 9.8,
    A: 39.1,
    Ix: 3890,
    Iy: 284,
    rx: 9.97,
    ry: 2.69,
    Welx: 324,
    Wely: 47.3,
    Zx: 367,
    Zy: 73.9,
    weightKgM: 30.7,
    description: 'Perfil IPE 240 con excelente relación resistencia/peso.',
  },
  {
    id: 'IPE_300',
    type: 'W_SHAPE',
    category: 'hot_rolled',
    family: 'IPE',
    designation: 'IPE 300',
    standardRef: 'EN 10034 / Eurocódigo 3',
    d: 300,
    b: 150,
    tw: 7.1,
    tf: 10.7,
    A: 53.8,
    Ix: 8360,
    Iy: 604,
    rx: 12.5,
    ry: 3.35,
    Welx: 557,
    Wely: 80.5,
    Zx: 628,
    Zy: 125,
    weightKgM: 42.2,
    description: 'Perfil IPE 300 para columnas principales de pórticos industriales.',
  },

  // --------------------------------------------------------------------------
  // PERFILES HEB (Vigas H de alas anchas - Secciones óptimas para columnas)
  // --------------------------------------------------------------------------
  {
    id: 'HEB_160',
    type: 'W_SHAPE',
    category: 'hot_rolled',
    family: 'HEB',
    designation: 'HEB 160',
    standardRef: 'EN 10034 / DIN 1025-2',
    d: 160,
    b: 160,
    tw: 8.0,
    tf: 13.0,
    A: 54.3,
    Ix: 2490,
    Iy: 889,
    rx: 6.78,
    ry: 4.05,
    Welx: 311,
    Wely: 111,
    Zx: 354,
    Zy: 170,
    weightKgM: 42.6,
    description: 'Perfil HEB simétrico idóneo para columnas sometidas a compresión biaxial.',
  },
  {
    id: 'HEB_200',
    type: 'W_SHAPE',
    category: 'hot_rolled',
    family: 'HEB',
    designation: 'HEB 200',
    standardRef: 'EN 10034 / DIN 1025-2',
    d: 200,
    b: 200,
    tw: 9.0,
    tf: 15.0,
    A: 78.1,
    Ix: 5700,
    Iy: 2000,
    rx: 8.54,
    ry: 5.07,
    Welx: 570,
    Wely: 200,
    Zx: 643,
    Zy: 306,
    weightKgM: 61.3,
    description: 'Perfil HEB 200 para pilares de edificios de varios niveles.',
  },
  {
    id: 'HEB_240',
    type: 'W_SHAPE',
    category: 'hot_rolled',
    family: 'HEB',
    designation: 'HEB 240',
    standardRef: 'EN 10034 / DIN 1025-2',
    d: 240,
    b: 240,
    tw: 10.0,
    tf: 17.0,
    A: 106.0,
    Ix: 11260,
    Iy: 3920,
    rx: 10.3,
    ry: 6.08,
    Welx: 938,
    Wely: 327,
    Zx: 1053,
    Zy: 498,
    weightKgM: 83.2,
    description: 'Perfil HEB 240 de alta rigidez en ambos planos de pandeo.',
  },
  {
    id: 'HEB_300',
    type: 'W_SHAPE',
    category: 'hot_rolled',
    family: 'HEB',
    designation: 'HEB 300',
    standardRef: 'EN 10034 / DIN 1025-2',
    d: 300,
    b: 300,
    tw: 11.0,
    tf: 19.0,
    A: 149.0,
    Ix: 25170,
    Iy: 8560,
    rx: 13.0,
    ry: 7.58,
    Welx: 1680,
    Wely: 571,
    Zx: 1869,
    Zy: 870,
    weightKgM: 117.0,
    description: 'Perfil HEB 300 para columnas pesadas de edificios comerciales.',
  },

  // --------------------------------------------------------------------------
  // PERFILES HEA (Vigas H aligeradas - Secciones eficientes)
  // --------------------------------------------------------------------------
  {
    id: 'HEA_200',
    type: 'W_SHAPE',
    category: 'hot_rolled',
    family: 'HEA',
    designation: 'HEA 200',
    standardRef: 'EN 10034 / DIN 1025-3',
    d: 190,
    b: 200,
    tw: 6.5,
    tf: 10.0,
    A: 53.8,
    Ix: 3690,
    Iy: 1340,
    rx: 8.28,
    ry: 4.98,
    Welx: 389,
    Wely: 134,
    Zx: 430,
    Zy: 204,
    weightKgM: 42.3,
    description: 'Perfil HEA 200 con excelente inercia en eje débil y menor peso.',
  },
  {
    id: 'HEA_240',
    type: 'W_SHAPE',
    category: 'hot_rolled',
    family: 'HEA',
    designation: 'HEA 240',
    standardRef: 'EN 10034 / DIN 1025-3',
    d: 230,
    b: 240,
    tw: 7.5,
    tf: 12.0,
    A: 76.8,
    Ix: 7760,
    Iy: 2770,
    rx: 10.1,
    ry: 6.0,
    Welx: 675,
    Wely: 231,
    Zx: 745,
    Zy: 352,
    weightKgM: 60.3,
    description: 'Perfil HEA 240 aligerado para marcos sismorresistentes.',
  },

  // --------------------------------------------------------------------------
  // PERFILES UPN (Perfiles en U laminados en caliente - EN 10025)
  // --------------------------------------------------------------------------
  {
    id: 'UPN_160',
    type: 'W_SHAPE',
    category: 'hot_rolled',
    family: 'UPN',
    designation: 'UPN 160',
    standardRef: 'DIN 1026-1 / NC Acero',
    d: 160,
    b: 65,
    tw: 7.5,
    tf: 10.5,
    A: 24.0,
    Ix: 925,
    Iy: 85.3,
    rx: 6.21,
    ry: 1.89,
    Welx: 116,
    Wely: 18.3,
    Zx: 138,
    Zy: 35.2,
    weightKgM: 18.8,
    description: 'Perfil U normalizado para columnas compuestas presilladas o en cajón.',
  },
  {
    id: 'UPN_200',
    type: 'W_SHAPE',
    category: 'hot_rolled',
    family: 'UPN',
    designation: 'UPN 200',
    standardRef: 'DIN 1026-1 / NC Acero',
    d: 200,
    b: 75,
    tw: 8.5,
    tf: 11.5,
    A: 32.2,
    Ix: 1910,
    Iy: 148,
    rx: 7.7,
    ry: 2.14,
    Welx: 191,
    Wely: 27.0,
    Zx: 228,
    Zy: 51.5,
    weightKgM: 25.3,
    description: 'Perfil UPN 200 usado frecuentemente en columnas dobles o pórticos.',
  },
  {
    id: 'UPN_240',
    type: 'W_SHAPE',
    category: 'hot_rolled',
    family: 'UPN',
    designation: 'UPN 240',
    standardRef: 'DIN 1026-1 / NC Acero',
    d: 240,
    b: 85,
    tw: 9.5,
    tf: 13.0,
    A: 42.3,
    Ix: 3600,
    Iy: 248,
    rx: 9.22,
    ry: 2.42,
    Welx: 300,
    Wely: 39.6,
    Zx: 360,
    Zy: 75.0,
    weightKgM: 33.2,
    description: 'Perfil UPN 240 de alta resistencia.',
  },

  // --------------------------------------------------------------------------
  // PERFILES W AMERICANOS (AISC 360 - Wide Flange)
  // --------------------------------------------------------------------------
  {
    id: 'W8x31',
    type: 'W_SHAPE',
    category: 'hot_rolled',
    family: 'W_SHAPE',
    designation: 'W8x31',
    standardRef: 'AISC 360-16 / ASTM A6',
    d: 203,
    b: 203,
    tw: 7.24,
    tf: 11.05,
    A: 58.8,
    Ix: 4580,
    Iy: 1540,
    rx: 8.81,
    ry: 5.13,
    Welx: 451,
    Wely: 152,
    Zx: 505,
    Zy: 233,
    weightKgM: 46.1,
    description: 'Columna estándar americana de 8 pulgadas cuadradas (AISC).',
  },
  {
    id: 'W10x45',
    type: 'W_SHAPE',
    category: 'hot_rolled',
    family: 'W_SHAPE',
    designation: 'W10x45',
    standardRef: 'AISC 360-16 / ASTM A6',
    d: 257,
    b: 204,
    tw: 8.89,
    tf: 15.75,
    A: 85.8,
    Ix: 10300,
    Iy: 2220,
    rx: 11.0,
    ry: 5.1,
    Welx: 802,
    Wely: 218,
    Zx: 890,
    Zy: 325,
    weightKgM: 67.0,
    description: 'Columna W10 pesada de alta resistencia axial y ductilidad.',
  },
  {
    id: 'W12x65',
    type: 'W_SHAPE',
    category: 'hot_rolled',
    family: 'W_SHAPE',
    designation: 'W12x65',
    standardRef: 'AISC 360-16 / ASTM A6',
    d: 307,
    b: 305,
    tw: 9.91,
    tf: 15.37,
    A: 123.0,
    Ix: 22200,
    Iy: 7240,
    rx: 13.4,
    ry: 7.7,
    Welx: 1450,
    Wely: 475,
    Zx: 1590,
    Zy: 710,
    weightKgM: 96.7,
    description: 'Columna W12x65 de ala ancha, excelente para pórticos sismorresistentes (SMF).',
  },
  {
    id: 'W14x90',
    type: 'W_SHAPE',
    category: 'hot_rolled',
    family: 'W_SHAPE',
    designation: 'W14x90',
    standardRef: 'AISC 360-16 / ASTM A6',
    d: 356,
    b: 368,
    tw: 11.18,
    tf: 18.03,
    A: 171.0,
    Ix: 41600,
    Iy: 15000,
    rx: 15.6,
    ry: 9.4,
    Welx: 2340,
    Wely: 815,
    Zx: 2570,
    Zy: 1220,
    weightKgM: 134.0,
    description: 'Columna W14x90 para cargas elevadas y rascacielos.',
  },

  // --------------------------------------------------------------------------
  // PERFILES CONFORMADOS EN FRÍO: PERFILES C (Chapa plegada / Light-gauge)
  // --------------------------------------------------------------------------
  {
    id: 'CF_C_150x50x2.5',
    type: 'BOX_BUILT',
    category: 'cold_formed',
    family: 'C_CHANNEL',
    designation: 'C 150x50x2.5 (Conformado en Frío)',
    standardRef: 'EN 10162 / AISI S100',
    d: 150,
    b: 50,
    tw: 2.5,
    tf: 2.5,
    A: 6.35,
    Ix: 215,
    Iy: 18.4,
    rx: 5.82,
    ry: 1.7,
    Welx: 28.7,
    Wely: 5.4,
    Zx: 34.5,
    Zy: 9.2,
    weightKgM: 4.98,
    description: 'Canal C conformado en frío de chapa galvanizada para estructuras ligeras.',
  },
  {
    id: 'CF_C_200x60x3.0',
    type: 'BOX_BUILT',
    category: 'cold_formed',
    family: 'C_CHANNEL',
    designation: 'C 200x60x3.0 (Conformado en Frío)',
    standardRef: 'EN 10162 / AISI S100',
    d: 200,
    b: 60,
    tw: 3.0,
    tf: 3.0,
    A: 9.85,
    Ix: 568,
    Iy: 39.5,
    rx: 7.59,
    ry: 2.0,
    Welx: 56.8,
    Wely: 9.5,
    Zx: 67.8,
    Zy: 16.5,
    weightKgM: 7.73,
    description: 'Canal C 200 mm para columnas de entramados ligeros y naves pequeñas.',
  },
  {
    id: 'CF_C_250x75x3.0',
    type: 'BOX_BUILT',
    category: 'cold_formed',
    family: 'C_CHANNEL',
    designation: 'C 250x75x3.0 (Conformado en Frío)',
    standardRef: 'EN 10162 / AISI S100',
    d: 250,
    b: 75,
    tw: 3.0,
    tf: 3.0,
    A: 12.5,
    Ix: 1110,
    Iy: 78.5,
    rx: 9.42,
    ry: 2.5,
    Welx: 88.8,
    Wely: 15.2,
    Zx: 105.0,
    Zy: 26.8,
    weightKgM: 9.81,
    description: 'Canal C 250x75 de gran altura para soportes no arriostrados ligeros.',
  },

  // --------------------------------------------------------------------------
  // PERFILES CONFORMADOS EN FRÍO: PERFILES Z
  // --------------------------------------------------------------------------
  {
    id: 'CF_Z_200x60x2.5',
    type: 'BOX_BUILT',
    category: 'cold_formed',
    family: 'Z_PROFILE',
    designation: 'Z 200x60x2.5 (Conformado en Frío)',
    standardRef: 'EN 10162 / AISI S100',
    d: 200,
    b: 60,
    tw: 2.5,
    tf: 2.5,
    A: 8.25,
    Ix: 480,
    Iy: 52.0,
    rx: 7.62,
    ry: 2.51,
    Welx: 48.0,
    Wely: 12.0,
    Zx: 57.0,
    Zy: 19.5,
    weightKgM: 6.48,
    description: 'Perfil Z asimétrico conformado en frío, común en cerramientos y pilares secundarios.',
  },

  // --------------------------------------------------------------------------
  // PERFILES TUBULARES CUADRADOS Y RECTANGULARES (HSS conformados en frío EN 10219 / ASTM A500)
  // --------------------------------------------------------------------------
  {
    id: 'HSS_100x100x4',
    type: 'HSS_RECT',
    category: 'cold_formed',
    family: 'HSS_RECT',
    designation: 'HSS 100x100x4.0 (Tubo Cuadrado)',
    standardRef: 'EN 10219 / ASTM A500 Gr. B',
    d: 100,
    b: 100,
    tw: 4.0,
    tf: 4.0,
    A: 15.0,
    Ix: 231,
    Iy: 231,
    rx: 3.92,
    ry: 3.92,
    Welx: 46.2,
    Wely: 46.2,
    Zx: 55.4,
    Zy: 55.4,
    weightKgM: 11.8,
    description: 'Tubo cuadrado compacto conformado en frío, altamente eficiente contra pandeo torsional.',
  },
  {
    id: 'HSS_150x150x6',
    type: 'HSS_RECT',
    category: 'cold_formed',
    family: 'HSS_RECT',
    designation: 'HSS 150x150x6.0 (Tubo Cuadrado)',
    standardRef: 'EN 10219 / ASTM A500 Gr. B',
    d: 150,
    b: 150,
    tw: 6.0,
    tf: 6.0,
    A: 33.7,
    Ix: 1170,
    Iy: 1170,
    rx: 5.9,
    ry: 5.9,
    Welx: 156,
    Wely: 156,
    Zx: 184,
    Zy: 184,
    weightKgM: 26.5,
    description: 'Tubo cuadrado HSS 150x150 para columnas de naves y edificaciones comerciales.',
  },
  {
    id: 'HSS_200x200x8',
    type: 'HSS_RECT',
    category: 'cold_formed',
    family: 'HSS_RECT',
    designation: 'HSS 200x200x8.0 (Cajón Cuadrado)',
    standardRef: 'EN 10219 / ASTM A500 Gr. B',
    d: 200,
    b: 200,
    tw: 8.0,
    tf: 8.0,
    A: 59.2,
    Ix: 3600,
    Iy: 3600,
    rx: 7.8,
    ry: 7.8,
    Welx: 360,
    Wely: 360,
    Zx: 420,
    Zy: 420,
    weightKgM: 46.5,
    description: 'Columna tubular cuadrada pesada, excelente resistencia biaxial sin pandeo lateral.',
  },
  {
    id: 'HSS_250x250x10',
    type: 'HSS_RECT',
    category: 'cold_formed',
    family: 'HSS_RECT',
    designation: 'HSS 250x250x10 (Cajón Pesado)',
    standardRef: 'EN 10219 / ASTM A500 Gr. B',
    d: 250,
    b: 250,
    tw: 10.0,
    tf: 10.0,
    A: 93.6,
    Ix: 8900,
    Iy: 8900,
    rx: 9.75,
    ry: 9.75,
    Welx: 712,
    Wely: 712,
    Zx: 860,
    Zy: 860,
    weightKgM: 73.5,
    description: 'Cajón estructural de 250 mm para cargas axiales severas y pórticos sismorresistentes.',
  },
  {
    id: 'HSS_200x100x6',
    type: 'HSS_RECT',
    category: 'cold_formed',
    family: 'HSS_RECT',
    designation: 'HSS 200x100x6.0 (Tubo Rectangular)',
    standardRef: 'EN 10219 / ASTM A500 Gr. B',
    d: 200,
    b: 100,
    tw: 6.0,
    tf: 6.0,
    A: 33.7,
    Ix: 1720,
    Iy: 564,
    rx: 7.15,
    ry: 4.09,
    Welx: 172,
    Wely: 113,
    Zx: 212,
    Zy: 132,
    weightKgM: 26.5,
    description: 'Tubo rectangular conformado en frío para columnas con dirección predominante de flexión.',
  },

  // --------------------------------------------------------------------------
  // TUBOS CIRCULARES (CHS - Circular Hollow Sections)
  // --------------------------------------------------------------------------
  {
    id: 'CHS_114x4.5',
    type: 'HSS_ROUND',
    category: 'cold_formed',
    family: 'HSS_ROUND',
    designation: 'CHS Ø114.3x4.5 (Tubo Circular)',
    standardRef: 'EN 10219 / ASTM A500',
    d: 114.3,
    b: 114.3,
    tw: 4.5,
    tf: 4.5,
    A: 15.5,
    Ix: 236,
    Iy: 236,
    rx: 3.9,
    ry: 3.9,
    Welx: 41.3,
    Wely: 41.3,
    Zx: 55.2,
    Zy: 55.2,
    weightKgM: 12.2,
    description: 'Tubo circular simétrico en 360°, nulo coeficiente de arrastre al viento.',
  },
  {
    id: 'CHS_168x6',
    type: 'HSS_ROUND',
    category: 'cold_formed',
    family: 'HSS_ROUND',
    designation: 'CHS Ø168.3x6.3 (Tubo Circular)',
    standardRef: 'EN 10219 / ASTM A500',
    d: 168.3,
    b: 168.3,
    tw: 6.3,
    tf: 6.3,
    A: 32.1,
    Ix: 1060,
    Iy: 1060,
    rx: 5.75,
    ry: 5.75,
    Welx: 126,
    Wely: 126,
    Zx: 168,
    Zy: 168,
    weightKgM: 25.2,
    description: 'Tubo circular de 168 mm para columnas arquitectónicas expuestas a viento.',
  },
  {
    id: 'CHS_219x8',
    type: 'HSS_ROUND',
    category: 'cold_formed',
    family: 'HSS_ROUND',
    designation: 'CHS Ø219.1x8.0 (Tubo Circular Pesado)',
    standardRef: 'EN 10219 / ASTM A500',
    d: 219.1,
    b: 219.1,
    tw: 8.0,
    tf: 8.0,
    A: 53.1,
    Ix: 2980,
    Iy: 2980,
    rx: 7.5,
    ry: 7.5,
    Welx: 272,
    Wely: 272,
    Zx: 360,
    Zy: 360,
    weightKgM: 41.6,
    description: 'Tubo estructural circular pesado para columnas exentas de edificios y terminales.',
  },
];

// ============================================================================
// 2. EXTENDED WOOD DATABASE (MADERA TROPICAL CUBANA Y COMERCIALES EUROPEAS)
// ============================================================================

export interface ExtendedWoodProperties extends WoodProperties {
  family: 'NC_TROPICAL' | 'COMMERCIAL_SOFTWOOD' | 'COMMERCIAL_HARDWOOD' | 'GLULAM';
  standardRef: string;
  densityKgM3: number;
  description: string;
}

export const COMPLETE_WOOD_CATALOG: Record<string, ExtendedWoodProperties> = {
  NC_GRUPO_A: {
    id: 'NC_GRUPO_A',
    name: 'NC Grupo A (Maderas Duras Tropicales)',
    species: 'Caguairán, Júcaro, Yaití, Guayacán',
    family: 'NC_TROPICAL',
    standardRef: 'Norma Cubana NC 206:2002',
    speciesGroup: 'NC_GRUPO_A',
    fc0: 22.0, // Compresión paralela (MPa)
    ft0: 16.0, // Tracción paralela (MPa)
    fv: 3.5, // Cortante paralelo (MPa)
    E0mean: 16000, // Módulo elástico medio (MPa)
    E005: 12000, // Módulo elástico percentil 5% (MPa)
    densityKgM3: 980,
    serviceClass: 2,
    loadDuration: 'medium_term',
    kmod: 0.8,
    description: 'Maderas tropicales cubanas de densidad extrema, alta dureza y máxima resistencia al intemperismo y huracanes.',
  },
  NC_GRUPO_B: {
    id: 'NC_GRUPO_B',
    name: 'NC Grupo B (Maderas Semiduras)',
    species: 'Ocuje, Majagua, Algarrobo, Baría',
    family: 'NC_TROPICAL',
    standardRef: 'Norma Cubana NC 206:2002',
    speciesGroup: 'NC_GRUPO_B',
    fc0: 16.0,
    ft0: 11.5,
    fv: 2.6,
    E0mean: 12500,
    E005: 9500,
    densityKgM3: 780,
    serviceClass: 2,
    loadDuration: 'medium_term',
    kmod: 0.8,
    description: 'Maderas autóctonas de Cuba con gran equilibrio tenacidad-resistencia, ampliamente utilizadas en pórticos y cubiertas tradicionales.',
  },
  NC_GRUPO_C: {
    id: 'NC_GRUPO_C',
    name: 'NC Grupo C (Coníferas Autóctonas)',
    species: 'Pino Macho (Pinus caribaea var. caribaea), Cedro',
    family: 'NC_TROPICAL',
    standardRef: 'Norma Cubana NC 206:2002',
    speciesGroup: 'NC_GRUPO_C',
    fc0: 11.0,
    ft0: 8.0,
    fv: 2.0,
    E0mean: 9500,
    E005: 7000,
    densityKgM3: 580,
    serviceClass: 2,
    loadDuration: 'medium_term',
    kmod: 0.8,
    description: 'Pino caribeño cultivado en Pinar del Río y región oriental de Cuba, óptimo para postes y columnas de viviendas vernáculas.',
  },
  PINO_C24: {
    id: 'PINO_C24',
    name: 'Pino Estructural C24',
    species: 'Pino Silvestre / Radiata / Scots Pine',
    family: 'COMMERCIAL_SOFTWOOD',
    standardRef: 'Eurocódigo 5 (EN 338 / EN 1995-1-1)',
    speciesGroup: 'PINO_ESTRUCTURAL',
    fc0: 21.0,
    ft0: 14.0,
    fv: 4.0,
    E0mean: 11000,
    E005: 7400,
    densityKgM3: 420,
    serviceClass: 1,
    loadDuration: 'medium_term',
    kmod: 0.8,
    description: 'Conífera estructural estandarizada europea C24, material de referencia para construcción industrializada de madera.',
  },
  PINO_C18: {
    id: 'PINO_C18',
    name: 'Pino Comercial C18',
    species: 'Pino común comercial aserrado',
    family: 'COMMERCIAL_SOFTWOOD',
    standardRef: 'Eurocódigo 5 (EN 338)',
    speciesGroup: 'PINO_ESTRUCTURAL',
    fc0: 18.0,
    ft0: 11.0,
    fv: 3.4,
    E0mean: 9000,
    E005: 6000,
    densityKgM3: 380,
    serviceClass: 1,
    loadDuration: 'medium_term',
    kmod: 0.8,
    description: 'Madera de conífera de grado comercial estándar para estructuras secundarias.',
  },
  ROBLE_D40: {
    id: 'ROBLE_D40',
    name: 'Roble Europeo D40',
    species: 'Quercus robur / Frondosa densa',
    family: 'COMMERCIAL_HARDWOOD',
    standardRef: 'Eurocódigo 5 (EN 338)',
    speciesGroup: 'ROBLE_D40',
    fc0: 26.0,
    ft0: 18.0,
    fv: 4.0,
    E0mean: 13000,
    E005: 10500,
    densityKgM3: 660,
    serviceClass: 1,
    loadDuration: 'medium_term',
    kmod: 0.8,
    description: 'Madera noble de frondosa de alta tenacidad y resistencia mecánica superior.',
  },
  EUCALIPTO_D30: {
    id: 'EUCALIPTO_D30',
    name: 'Eucalipto Blanco D30',
    species: 'Eucalyptus globulus',
    family: 'COMMERCIAL_HARDWOOD',
    standardRef: 'Eurocódigo 5 (EN 338)',
    speciesGroup: 'ROBLE_D40',
    fc0: 23.0,
    ft0: 15.0,
    fv: 3.5,
    E0mean: 12000,
    E005: 9000,
    densityKgM3: 640,
    serviceClass: 1,
    loadDuration: 'medium_term',
    kmod: 0.8,
    description: 'Madera densa de rápido crecimiento, muy utilizada en pilares agrícolas y pérgolas.',
  },
  GLULAM_GL24h: {
    id: 'GLULAM_GL24h',
    name: 'Madera Laminada Encolada GL24h',
    species: 'Pino laminado homogéneo con adhesivo estructural',
    family: 'GLULAM',
    standardRef: 'Eurocódigo 5 (EN 14080)',
    speciesGroup: 'PINO_ESTRUCTURAL',
    fc0: 24.0,
    ft0: 19.2,
    fv: 3.5,
    E0mean: 11500,
    E005: 9600,
    densityKgM3: 420,
    serviceClass: 1,
    loadDuration: 'medium_term',
    kmod: 0.8,
    description: 'Vigas y pilares de madera laminada homogénea sin nudos críticos, alta estabilidad dimensional.',
  },
};

// ============================================================================
// 3. EXTENDED CONCRETE MIXES (EUROCODE, ACI 318 & NORMA CUBANA NC 450)
// ============================================================================

export interface ExtendedConcreteMaterial {
  id: string;
  name: string;
  eurocodeClass: string; // ej: "C20/25", "C25/30"
  cubeStrength: number; // MPa probeta cúbica (R_cube o fck,cube)
  fc: number; // MPa probeta cilíndrica f'c (ACI) o fck (Eurocódigo)
  Rb_NC: number; // Resistencia de cálculo a compresión Rb según NC 450 (MPa)
  fctm: number; // Resistencia media a tracción por flexión (MPa)
  Ec: number; // Módulo de deformación longitudinal Ecm (MPa)
  density: number; // kg/m³
  standardRef: string;
  description: string;
}

export const COMPLETE_CONCRETE_CATALOG: Record<string, ExtendedConcreteMaterial> = {
  H20: {
    id: 'H20',
    name: 'C16/20 (H-20) Hormigón Ligero / Cimentaciones',
    eurocodeClass: 'C16/20',
    cubeStrength: 20,
    fc: 20,
    Rb_NC: 11.5,
    fctm: 1.9,
    Ec: 21000,
    density: 2400,
    standardRef: 'NC 450 / Eurocódigo 2',
    description: 'Hormigón para zapatas corridas, muros de contención y columnas de baja carga en 1-2 plantas.',
  },
  H25: {
    id: 'H25',
    name: 'C20/25 (H-25) Estándar Estructural Cuba & LatAm',
    eurocodeClass: 'C20/25',
    cubeStrength: 25,
    fc: 25,
    Rb_NC: 14.5,
    fctm: 2.2,
    Ec: 23500,
    density: 2400,
    standardRef: 'NC 450:2006 / ACI 318 / EC2',
    description: 'Hormigón más empleado en edificaciones residenciales e institucionales en Cuba y el Caribe.',
  },
  H30: {
    id: 'H30',
    name: 'C25/30 (H-30) Estructural Porticado Superior',
    eurocodeClass: 'C25/30',
    cubeStrength: 30,
    fc: 30,
    Rb_NC: 17.0,
    fctm: 2.6,
    Ec: 25700,
    density: 2400,
    standardRef: 'NC 450 / ACI 318-19',
    description: 'Recomendado para pórticos sismorresistentes, columnas de 3 a 8 plantas y ambientes marinos.',
  },
  H35: {
    id: 'H35',
    name: 'C30/37 (H-35) Alta Resistencia Sísmica',
    eurocodeClass: 'C30/37',
    cubeStrength: 37,
    fc: 35,
    Rb_NC: 19.5,
    fctm: 2.9,
    Ec: 27800,
    density: 2400,
    standardRef: 'ACI 318-19 Cap. 18 / EC2',
    description: 'Hormigón de alto desempeño para zonas de sismicidad severa (Santiago de Cuba) y alta ductilidad.',
  },
  H40: {
    id: 'H40',
    name: 'C35/45 (H-40) Edificios Altos y Puentes',
    eurocodeClass: 'C35/45',
    cubeStrength: 45,
    fc: 40,
    Rb_NC: 22.0,
    fctm: 3.2,
    Ec: 29700,
    density: 2400,
    standardRef: 'ACI 318 / Eurocódigo 2',
    description: 'Columnas de plantas bajas en rascacielos con fuerte carga axial y control de deformaciones P-Delta.',
  },
  H50: {
    id: 'H50',
    name: 'C40/50 (H-50) Alto Rendimiento Durabilidad',
    eurocodeClass: 'C40/50',
    cubeStrength: 50,
    fc: 50,
    Rb_NC: 25.5,
    fctm: 3.5,
    Ec: 31500,
    density: 2450,
    standardRef: 'ACI 318 / Eurocódigo 2',
    description: 'Hormigón de ultra-baja permeabilidad para torres costeras expuestas a niebla salina y huracanes.',
  },
  H60: {
    id: 'H60',
    name: 'C50/60 (H-60) Megaestructuras Especiales',
    eurocodeClass: 'C50/60',
    cubeStrength: 60,
    fc: 60,
    Rb_NC: 29.0,
    fctm: 4.1,
    Ec: 33000,
    density: 2500,
    standardRef: 'Eurocódigo 2 / ACI 318',
    description: 'Hormigón de muy alta resistencia con microsílice para núcleos de corte y megacolumnas.',
  },
};

// ============================================================================
// 4. STEEL MATERIALS (ACEROS ESTRUCTURALES Y BARRAS CORRUGADAS)
// ============================================================================

export interface ExtendedSteelMaterialItem extends SteelProperties {
  id: string;
  name: string;
  type: 'rebar' | 'structural_steel';
  Fy: number;
  Fu: number;
  E: number;
  standardRef: string;
  description: string;
}

export const COMPLETE_STEEL_MATERIALS: Record<string, ExtendedSteelMaterialItem> = {
  B500S: {
    id: 'B500S',
    name: 'B500S / B500D (Eurocódigo & NC 450)',
    type: 'rebar',
    grade: 'B500S',
    Fy: 500,
    Fu: 550,
    E: 200000,
    standardRef: 'UNE 36065 / NC 450',
    description: 'Acero corrugado para armaduras con límite elástico de 500 MPa y ductilidad C o S.',
  },
  Grado_60: {
    id: 'Grado_60',
    name: 'ASTM A615 / A706 Grado 60 (fy = 420 MPa)',
    type: 'rebar',
    grade: 'Grado_60',
    Fy: 420,
    Fu: 620,
    E: 200000,
    standardRef: 'ASTM A706 (Sismo-resistente soldable)',
    description: 'Acero de refuerzo más común en América, grado obligatorio para sismo según ACI 318-19.',
  },
  Grado_40: {
    id: 'Grado_40',
    name: 'ASTM A615 Grado 40 (fy = 280 MPa)',
    type: 'rebar',
    grade: 'Grado_40',
    Fy: 280,
    Fu: 490,
    E: 200000,
    standardRef: 'ASTM A615',
    description: 'Acero corrugado de resistencia moderada para obras rurales o secundarias.',
  },
  A36: {
    id: 'A36',
    name: 'ASTM A36 (Acero Estructural Comercial)',
    type: 'structural_steel',
    grade: 'A36',
    Fy: 250,
    Fu: 400,
    E: 200000,
    standardRef: 'ASTM A36 / AISC 360',
    description: 'Acero al carbono tradicional para placas base, ángulos y perfiles laminados estándar.',
  },
  A572_Gr50: {
    id: 'A572_Gr50',
    name: 'ASTM A572 Grado 50 (Perfiles W y Placas)',
    type: 'structural_steel',
    grade: 'A572_Gr50',
    Fy: 345,
    Fu: 450,
    E: 200000,
    standardRef: 'ASTM A572 / AISC 360',
    description: 'Acero de alta resistencia y baja aleación con 345 MPa de fluencia.',
  },
  A992: {
    id: 'A992',
    name: 'ASTM A992 (Sismo-resistente Perfiles W)',
    type: 'structural_steel',
    grade: 'A992',
    Fy: 345,
    Fu: 450,
    E: 200000,
    standardRef: 'ASTM A992 / AISC 341',
    description: 'El acero estándar exigido en vigas y columnas para pórticos sismorresistentes en EE.UU.',
  },
  S275: {
    id: 'S275',
    name: 'Eurocódigo S275 JR / JO',
    type: 'structural_steel',
    grade: 'S275',
    Fy: 275,
    Fu: 430,
    E: 210000,
    standardRef: 'EN 10025-2',
    description: 'Acero estructural europeo estándar para edificación industrial y civil.',
  },
  S355: {
    id: 'S355',
    name: 'Eurocódigo S355 J2 / K2',
    type: 'structural_steel',
    grade: 'S355',
    Fy: 355,
    Fu: 510,
    E: 210000,
    standardRef: 'EN 10025-2',
    description: 'Acero de alto límite elástico europeo de 355 MPa para estructuras solicitadas severamente.',
  },
  S250GD_CF: {
    id: 'S250GD_CF',
    name: 'S250GD Chapa Conformada en Frío Galvanizada',
    type: 'structural_steel',
    grade: 'S250GD',
    Fy: 250,
    Fu: 330,
    E: 205000,
    standardRef: 'EN 10346 / AISI S100',
    description: 'Chapa de acero galvanizada para perfiles conformados en frío tipo C, Z y tubos ligeros.',
  },
};
